name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'release_*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [ branch, tag ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/app
        run: |
          if [[ "${{ github.event_name }}" == "push" && "$GITHUB_REF" == "refs/heads/main" ]]; then
            docker build -t $IMAGE_NAME:latest .
            docker push $IMAGE_NAME:latest
          elif [[ "$GITHUB_REF" == refs/tags/release_* ]]; then
            VERSION=${GITHUB_REF#refs/tags/release_}
            docker build -t $IMAGE_NAME:$VERSION .
            docker push $IMAGE_NAME:$VERSION
          fi